### ISSUE TITLE
/form/pdf/:formID fails

### ISSUE THREAD

**Issue by Rpd-Strike** [TeamUnibuc/SmartForms#63]

**Comment by Rpd-Strike** [comment]
Getting the following log when trying to find the pdf string of a created form:

```
Traceback (most recent call last):
  File "C:\Users\Felix\.conda\envs\SmartForms\lib\site-packages\uvicorn\protocols\http\httptools_impl.py", line 372, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "C:\Users\Felix\.conda\envs\SmartForms\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "C:\Users\Felix\.conda\envs\SmartForms\lib\site-packages\fastapi\applications.py", line 261, in __call__
    await super().__call__(scope, receive, send)
  File "C:\Users\Felix\.conda\envs\SmartForms\lib\site-packages\starlette\applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\Felix\.conda\envs\SmartForms\lib\site-packages\starlette\middleware\errors.py", line 181, in __call__
    raise exc
  File "C:\Users\Felix\.conda\envs\SmartForms\lib\site-packages\starlette\middleware\errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "C:\Users\Felix\.conda\envs\SmartForms\lib\site-packages\starlette\middleware\sessions.py", line 77, in __call__
    await self.app(scope, receive, send_wrapper)
  File "C:\Users\Felix\.conda\envs\SmartForms\lib\site-packages\starlette\middleware\cors.py", line 84, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\Felix\.conda\envs\SmartForms\lib\site-packages\starlette\exceptions.py", line 82, in __call__
    raise exc
  File "C:\Users\Felix\.conda\envs\SmartForms\lib\site-packages\starlette\exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "C:\Users\Felix\.conda\envs\SmartForms\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 21, in __call__
    raise e
  File "C:\Users\Felix\.conda\envs\SmartForms\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\Felix\.conda\envs\SmartForms\lib\site-packages\starlette\routing.py", line 656, in __call__
    await route.handle(scope, receive, send)
  File "C:\Users\Felix\.conda\envs\SmartForms\lib\site-packages\starlette\routing.py", line 259, in handle
    await self.app(scope, receive, send)
  File "C:\Users\Felix\.conda\envs\SmartForms\lib\site-packages\starlette\routing.py", line 61, in app
    response = await func(request)
  File "C:\Users\Felix\.conda\envs\SmartForms\lib\site-packages\fastapi\routing.py", line 227, in app
    raw_response = await run_endpoint_function(
  File "C:\Users\Felix\.conda\envs\SmartForms\lib\site-packages\fastapi\routing.py", line 160, in run_endpoint_function
    return await dependant.call(**values)
  File "C:\Users\Felix\Desktop\SmartForms\backend\sources\routers\form_router.py", line 251, in get_form_pdf
    if not forms[0].canBeFilledOnline and request.session.get("user")["email"] != forms[0].authorEmail:
AttributeError: 'PdfForm' object has no attribute 'canBeFilledOnline'
```
